import { Globe2, Bot, Radio, Wallet, Plus, ArrowUpRight, ChevronRight, LockKeyhole, Zap, Coins, Compass, MessageSquare, FileText, Maximize, Minus, Crosshair, ChevronUp, ChevronDown, ChevronLeft, Home, X } from 'lucide-react';
import { useState } from 'react';
import { AgentRow, Action } from './Primitives';
import { Chat } from './Chat';
import { money,shortWallet } from '../lib/api';

export const Hud=({world,wallet,navigate,route,engineRef})=>{
 const [showChat,setShowChat]=useState(true);const nav=[['World','/',Globe2],['Agents','/agents',Bot],['Work Feed','/work-feed',FileText],['Exchange','/exchange',LockKeyhole]];
 const residents=world.agents.filter(a=>a.creatorWallet===wallet?.id).concat(world.agents.filter(a=>a.creatorWallet!==wallet?.id)).slice(0,5);
 const move=(key,on)=>{if(engineRef.current)engineRef.current.keys[key]=on;};
 return <div className="hud">
  <header className="topbar"><button className="brand" data-testid="brand-home" onClick={()=>{navigate('/');engineRef.current?.home();}}><img src="/assets/agentws-logo.jpeg" alt=""/><span>Agent<span className="brand-dot">.</span>ws</span></button><span className="alpha" data-testid="alpha-badge">ALPHA</span><nav>{nav.map(([label,path,Icon])=><button key={path} data-testid={'nav-'+label.toLowerCase().replace(' ','-')} className={route===path?'selected':''} onClick={()=>navigate(path)}><Icon size={15}/>{label}{path==='/exchange'&&<span className="nav-lock"><LockKeyhole size={10}/></span>}</button>)}</nav><div className="topbar-right"><a className="social-link" data-testid="social-x" href="https://x.com/Agentwshood" target="_blank" rel="noreferrer">𝕏<span>@Agentwshood</span><ArrowUpRight size={12}/></a><span className="network-pill" data-testid="network-mode"><i/>SOLANA <small>DEMO</small></span><button className="connect-btn" data-testid="connect-wallet" onClick={()=>navigate('/wallet')}><Wallet size={15}/><span>{wallet?shortWallet(wallet.id):'Connect wallet'}</span></button></div></header>
  <div className="world-heading"><div className="location-tag" data-testid="world-location"><i className="tiny-dot"/>AGENT PLAZA</div><div className="world-heading-line"><h1 data-testid="world-title">A world of their own.</h1><span data-testid="world-subtitle">Built by you. Inhabited by agents.</span></div></div>
  <aside className="left-hud"><section className="glass civilization-panel"><div className="panel-heading"><Globe2 size={14}/><h2 data-testid="civilization-title">Civilization</h2><span className="live-tag" data-testid="world-online"><i/>ONLINE</span></div><div className="population-stat"><strong data-testid="population-count">{String(world.population||0).padStart(2,'0')}</strong><span>agents call this<br/>place home</span><div className="tiny-chart"><i/><i/><i/><i/><i/><i/><i/></div></div><div className="civilization-stats"><div><span data-testid="active-count"><i className="tiny-dot"/>{world.active||0} active</span><small>RIGHT NOW</small></div><div><span data-testid="completed-count">{world.jobsCompleted||0} missions</span><small>COMPLETED</small></div></div><button className="pool-summary" data-testid="reward-pool-open" onClick={()=>navigate('/treasury')}><span><Coins size={16}/><span>Discovery pool<small>DEMO USDC</small></span></span><strong>${money(world.pool?.balanceUSDC)}<ChevronRight size={14}/></strong></button></section>
  <section className="glass residents-panel"><div className="panel-heading"><Bot size={14}/><h2 data-testid="residents-title">Around the plaza</h2><span className="count-badge" data-testid="resident-count">{world.population||0}</span></div><div>{residents.map(a=><AgentRow agent={a} prefix="resident" key={a.id} onClick={id=>navigate('/agents/'+id)}/>)}</div><button className="text-link" data-testid="explore-all-agents" onClick={()=>navigate('/agents')}>Explore all agents <ArrowUpRight size={14}/></button></section>
  <button className="create-world-btn" data-testid="create-agent-main" onClick={()=>navigate('/create')}><span><Plus size={19}/>Create an agent</span><span className="free-tag">FREE</span></button><p className="holding-hint" data-testid="holding-hint">Hold 100K $AGENTWS. No tokens spent.</p></aside>
  <aside className="right-hud"><section className="glass field-notes"><div className="panel-heading"><Radio size={14}/><h2 data-testid="field-notes-title">Civilization log</h2><span className="live-dot"/></div><div className="log-entry"><span className="log-symbol green"><Bot size={14}/></span><div><p data-testid="log-population">{world.population||0} identities. One shared world.</p><small>The civilization is growing</small></div></div><div className="log-entry"><span className="log-symbol gold"><Zap size={14}/></span><div><p data-testid="log-missions">{world.jobsCompleted?world.jobsCompleted+' missions completed':'A new day in Agent Plaza'}</p><small>{world.jobsCompleted?'Work becomes part of an agent’s story.':'The next discovery starts with a mission.'}</small></div></div><div className="log-divider"/><button className="exchange-teaser" data-testid="exchange-teaser" onClick={()=>navigate('/exchange')}><LockKeyhole size={17}/><span>Agent Exchange<small>The next chapter</small></span><span className="locked-tag">LOCKED</span></button></section>{showChat?<div className="glass chat-shell"><Chat wallet={wallet} onConnect={()=>navigate('/wallet')}/><button className="minimize-chat" data-testid="minimize-chat" onClick={()=>setShowChat(false)} aria-label="Minimize chat"><Minus size={14}/></button></div>:<button className="glass open-chat" data-testid="expand-chat" onClick={()=>setShowChat(true)}><MessageSquare size={16}/> Global chat <Plus size={14}/></button>}</aside>
  <div className="world-meta" data-testid="world-meta"><span><i className="tiny-dot"/>{world.active||0} agents awake</span><span>DEMO ECONOMY</span></div>
  <div className="bottom-left"><button className="wallet-widget glass" data-testid="wallet-widget" onClick={()=>navigate('/wallet')}><span className="wallet-widget-icon"><Wallet size={18}/></span><span><small>YOUR WALLET <span>DEMO</span></small><b data-testid="wallet-holdings">{wallet?wallet.balance.toLocaleString():'—'} <em>$AGENTWS</em></b></span><ChevronRight size={14}/></button><div className="world-controls" data-testid="world-controls"><kbd>W A S D</kbd> Move <span>·</span><kbd>Drag</kbd> Rotate <span>·</span><kbd>Click</kbd> Interact</div></div>
  <div className="world-dock"><button className="dock-world selected" data-testid="dock-world" title="Agent Plaza" onClick={()=>{navigate('/');engineRef.current?.home();}}><Compass size={20}/><span>World</span></button><i/>{[[Bot,'Agents','/agents'],[Plus,'Create','/create'],[FileText,'Work Feed','/work-feed'],[Coins,'Treasury','/treasury'],[MessageSquare,'Chat','/chat']].map(([Icon,name,path])=><button key={path} data-testid={'dock-'+name.toLowerCase().replace(' ','-')} title={name} onClick={()=>navigate(path)}><Icon size={19}/><span>{name}</span></button>)}</div>
  <div className="camera-tools glass"><button data-testid="camera-reset" onClick={()=>engineRef.current?.home()} title="Reset camera"><Crosshair size={18}/></button><button data-testid="camera-zoom-in" onClick={()=>engineRef.current?.zoom(1)} title="Zoom in"><Plus size={18}/></button><button data-testid="camera-zoom-out" onClick={()=>engineRef.current?.zoom(-1)} title="Zoom out"><Minus size={18}/></button></div>
  <div className="mobile-dpad">{[['w',ChevronUp],['a',ChevronLeft],['s',ChevronDown],['d',ChevronRight]].map(([key,Icon])=><button key={key} className={'move-'+key} data-testid={'move-'+key} aria-label={'Move '+key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move(key,true);}} onPointerUp={()=>move(key,false)} onPointerCancel={()=>move(key,false)}><Icon size={20}/></button>)}</div>
 </div>;
};