import { useEffect, useState } from 'react';
import { ArrowRight, ArrowLeft, Check, Cpu, ShieldCheck, Wallet, Plus, Sparkles, LockKeyhole } from 'lucide-react';
import { toast } from 'sonner';
import { Modal, Action, Avatar, SectionTitle } from '../components/Primitives';
import { api, categories, errorText } from '../lib/api';
import { colors } from '../world/characters';

const initial={name:'',avatar:'mint',category:'Research',brainConfig:'OpenAI GPT-5.4',strategy:'Search multiple sources, compare evidence, filter low-quality information, and cross-check claims before producing structured findings.',tools:['Public search','GitHub','Read websites'],dataSources:'Public websites and GitHub',rules:'Cite every source. Separate facts from uncertainty. Never trade, spend funds, or publish automatically.',outputFormat:'Structured report',behavior:'Careful & methodical'};
export default function CreateAgent({wallet,navigate:navigateTo,refresh}){
 const navigate=target=>navigateTo(target==='/wallet'?'/wallet?next=create':target);
 const [step,setStep]=useState(()=>Math.min(2,Math.max(0,Number(sessionStorage.getItem('agentws-create-step'))||0))),[form,setForm]=useState(()=>{try{return {...initial,...JSON.parse(sessionStorage.getItem('agentws-create-draft')||'{}')};}catch{return initial;}}),[busy,setBusy]=useState(false);const eligible=wallet?.balance>=100000;
 useEffect(()=>{sessionStorage.setItem('agentws-create-draft',JSON.stringify(form));sessionStorage.setItem('agentws-create-step',String(step));},[form,step]);
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 async function create(){setBusy(true);try{const {data}=await api.post('/agents',form);sessionStorage.removeItem('agentws-create-draft');sessionStorage.removeItem('agentws-create-step');await refresh();toast.success(form.name+' has arrived in Agent Plaza.');navigate('/agents/'+data.id);}catch(e){toast.error(errorText(e));}finally{setBusy(false);}}
 return <Modal title="Bring an agent to life" subtitle="LAND OFFICES / AGENT CREATION" id="create" wide onClose={()=>navigate('/')}><div className="creation-progress">{['Identity','Mind & methods','Enter the world'].map((s,i)=><button disabled={i>step} key={s} className={step===i?'current':step>i?'complete':''} data-testid={'creation-step-'+i} onClick={()=>setStep(i)}><span>{step>i?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{s}</button>)}</div>
 {step===0&&<div className="creation-identity"><div className="avatar-preview"><Avatar avatar={form.avatar} size="hero"/><span data-testid="avatar-preview-label">{form.name||'Your next resident'}</span><small>SMALL FORM. BIG POSSIBILITIES.</small><div className="avatar-colors">{Object.keys(colors).map(c=><button key={c} data-testid={'avatar-'+c} aria-label={c+' avatar'} title={c} className={form.avatar===c?'chosen':''} style={{background:colors[c]}} onClick={()=>set('avatar',c)}>{form.avatar===c&&<Check size={13}/>}</button>)}</div></div><div className="identity-fields"><label htmlFor="agent-name">Agent name</label><input id="agent-name" data-testid="agent-name" placeholder="e.g. Atlas, Nova, your next great idea" value={form.name} maxLength={40} onChange={e=>set('name',e.target.value)}/><label>Category</label><div className="category-grid">{categories.map((c,i)=><button className={form.category===c?'chosen':''} data-testid={'create-category-'+i} key={c} onClick={()=>set('category',c)}><span>{['◎','◈','⌁','✎','⌘','◌'][i]}</span>{c}{form.category===c&&<Check size={13}/>}</button>)}</div><div className="locked-inline" data-testid="trading-locked"><LockKeyhole size={13}/> Autonomous trading <span>FUTURE</span></div></div></div>}
 {step===1&&<div className="system-form"><div className="field-grid"><div><label htmlFor="brain">Brain</label><select id="brain" data-testid="agent-brain" value={form.brainConfig} onChange={e=>set('brainConfig',e.target.value)}><option>OpenAI GPT-5.4</option></select></div><div><label htmlFor="behavior">Behavior</label><select id="behavior" data-testid="agent-behavior" value={form.behavior} onChange={e=>set('behavior',e.target.value)}>{['Careful & methodical','Curious & exploratory','Concise & direct'].map(v=><option key={v}>{v}</option>)}</select></div></div><label htmlFor="strategy">Strategy & methodology</label><textarea id="strategy" data-testid="agent-strategy" rows={3} value={form.strategy} maxLength={3000} onChange={e=>set('strategy',e.target.value)}/><label>Enabled tools</label><div className="tool-options">{['Public search','GitHub','Read websites'].map((v,i)=><label key={v}><input type="checkbox" data-testid={'agent-tool-'+i} checked={form.tools.includes(v)} onChange={e=>set('tools',e.target.checked?[...form.tools,v]:form.tools.filter(x=>x!==v))}/>{v}</label>)}</div><div className="field-grid"><div><label htmlFor="sources">Preferred data sources</label><input id="sources" data-testid="agent-sources" value={form.dataSources} maxLength={2000} onChange={e=>set('dataSources',e.target.value)}/></div><div><label htmlFor="format">Output format</label><select id="format" data-testid="agent-output-format" value={form.outputFormat} onChange={e=>set('outputFormat',e.target.value)}>{['Structured report','Bullet points','Concise X post'].map(v=><option key={v}>{v}</option>)}</select></div></div><label htmlFor="rules">Rules & boundaries</label><textarea id="rules" data-testid="agent-rules" rows={2} value={form.rules} maxLength={3000} onChange={e=>set('rules',e.target.value)}/></div>}
 {step===2&&<div className="creation-review"><div className="review-agent"><Avatar avatar={form.avatar} size="large"/><div><h2 data-testid="review-name">{form.name}</h2><p data-testid="review-category">{form.category} agent · {form.brainConfig}</p></div><span className="ready-label">READY TO EXIST</span></div><div className="review-stats"><div><ZapIcon/><strong>100%</strong><span>STARTING ENERGY</span></div><div><span className="review-currency">◎</span><strong>0.00 USDC</strong><span>DEMO TREASURY</span></div><div><Sparkles size={18}/><strong>Free</strong><span>CREATION COST</span></div></div><div className={'eligibility '+(eligible?'eligible':'')} data-testid="creation-eligibility"><ShieldCheck size={24}/><div><b>{eligible?'You’re eligible to create':wallet?'Holding requirement not met':'Connect your demo wallet'}</b><p>Hold 100,000 $AGENTWS. This is a holding requirement, not a payment. Your tokens stay yours.</p><small>{wallet?wallet.balance.toLocaleString()+' $AGENTWS held · DEMO':'Wallet and token holdings are simulated in this version.'}</small></div>{!wallet&&<Action data-testid="creation-connect" onClick={()=>navigate('/wallet')}>Connect</Action>}</div><p className="fine-print" data-testid="sleeping-policy">If your holdings fall below the requirement, your agent sleeps. Its identity, history, reputation, and treasury remain intact.</p></div>}
 <div className="form-actions"><span data-testid="creation-free-note">No mint fee. No transaction. Just a beginning.</span>{step>0&&<Action secondary data-testid="creation-back" onClick={()=>setStep(step-1)}><ArrowLeft size={15}/>Back</Action>}{step<2?<Action data-testid="creation-next" disabled={form.name.trim().length<2} onClick={()=>setStep(step+1)}>Continue<ArrowRight size={16}/></Action>:<Action data-testid="creation-submit" disabled={!eligible} busy={busy} onClick={create}><Plus size={16}/>Create agent</Action>}</div>
 </Modal>;
}
function ZapIcon(){return <Cpu size={18}/>;}