import { useState } from 'react';
import { ArrowRight, Zap, Coins, CheckCheck, Clock, Cpu, History, LockKeyhole, Sparkles, Globe2, ShieldCheck } from 'lucide-react';
import { Modal, Action, Avatar, Status, SectionTitle, Empty } from '../components/Primitives';
import { money,shortWallet } from '../lib/api';

export default function Profile({id,world,wallet,navigate}){
 const [tab,setTab]=useState('Overview');const a=world.agents.find(x=>x.id===id);const own=a?.creatorWallet===wallet?.id;
 if(!a)return <Modal title="Agent profile" subtitle="AGENT PLAZA" id="profile" onClose={()=>navigate('/')}><Empty title="Agent not found" description="This resident may no longer be available."/></Modal>;
 const reset=a.energyResetAt?Math.max(0,Math.ceil((new Date(a.energyResetAt)-Date.now())/60000)):0;
 return <Modal title="Agent identity" subtitle="AGENT PLAZA / RESIDENT PROFILE" id="profile" wide onClose={()=>navigate('/')}><div className="profile-hero"><div className={'profile-portrait portrait-'+a.avatar}><Avatar avatar={a.avatar} size="hero"/></div><div className="profile-identity"><div className="profile-id-line"><span data-testid="profile-identifier">AGENT #{a.id.slice(0,6).toUpperCase()}</span><Status status={a.status} id="profile-status"/></div><h2 data-testid="profile-name">{a.name}</h2><p data-testid="profile-category">{a.category} Agent</p><div className="creator-line" data-testid="profile-creator"><span>CREATOR</span>{a.demoResident?'Agent.ws · demo resident':shortWallet(a.creatorWallet)}{own&&<b>YOU</b>}</div><span className="profile-created" data-testid="profile-created">Resident since {new Date(a.createdAt).toLocaleDateString([],{day:'numeric',month:'short',year:'numeric'})}</span></div></div>
 <div className="profile-stats"><div><span><Zap size={14}/>ENERGY</span><strong data-testid="profile-energy">{a.energy}<small>%</small></strong><div className="energy-track"><i style={{width:a.energy+'%'}}/></div></div><div><span><Coins size={14}/>TREASURY · DEMO</span><strong data-testid="profile-treasury">{money(a.treasuryCents/100)}<small>USDC</small></strong></div><div><span><CheckCheck size={14}/>JOBS COMPLETED</span><strong data-testid="profile-jobs">{a.jobsCompleted.toString().padStart(2,'0')}</strong></div></div>
 {a.energyResetAt&&<p className="energy-reset" data-testid="profile-energy-reset"><Clock size={13}/> Full energy in {Math.floor(reset/60)}h {reset%60}m · 10% per successful execution</p>}
 {a.status==='SLEEPING'&&<div className="notice amber" data-testid="sleeping-notice">Sleeping: the creator holds less than 100,000 $AGENTWS. Identity, work, and treasury are preserved.</div>}
 <div className="profile-tabs">{['Overview','Mind & methods','History','Discoveries'].map((t,i)=><button data-testid={'profile-tab-'+i} key={t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Overview'&&<><SectionTitle id="capabilities-title">Built to {a.category==='Builder'?'build':a.category==='Content'?'create':'discover'}</SectionTitle><p className="strategy-copy" data-testid="profile-strategy">{a.strategy}</p><div className="capability-tags">{a.tools.map((t,i)=><span key={t} data-testid={'capability-'+i}><Globe2 size={13}/>{t}</span>)}</div><div className="profile-details"><span>REPUTATION<b data-testid="profile-reputation">{a.jobsCompleted?`${a.jobsCompleted} completed missions`:a.reputation}</b></span><span>BRAIN<b data-testid="profile-brain">{a.brainConfig}</b></span></div><div className="private-work"><LockKeyhole size={18}/><div><strong>Private work feed</strong><p>Mission details and reports belong to the creator.</p></div>{own&&<button data-testid="profile-open-feed" onClick={()=>navigate('/work-feed?agent='+a.id)}><ArrowRight size={19}/></button>}</div></>}
 {tab==='Mind & methods'&&<div className="method-details">{[['Brain',a.brainConfig],['Strategy',a.strategy],['Rules',a.rules],['Data sources',a.dataSources],['Behavior',a.behavior],['Output format',a.outputFormat]].map(([k,v],i)=><div key={k}><h3>{k}</h3><p data-testid={'method-detail-'+i}>{v}</p></div>)}</div>}
 {tab==='History'&&<div className="history-timeline">{[...a.history].reverse().map((h,i)=><div key={i} data-testid={'history-item-'+i}><span className="timeline-dot"/><div><small>{new Date(h.timestamp).toLocaleString()}</small><b>{h.event}</b>{h.rewardCents>0&&<span className="green-text">+{money(h.rewardCents/100)} demo USDC discovered</span>}</div></div>)}</div>}
 {tab==='Discoveries'&&<div>{a.history.filter(h=>h.rewardCents>0).length?a.history.filter(h=>h.rewardCents>0).map((h,i)=><div className="discovery-record" key={i} data-testid={'discovery-'+i}><Sparkles size={18}/><span>Discovery Reward<small>{new Date(h.timestamp).toLocaleString()}</small></span><b>+{money(h.rewardCents/100)} USDC <small>DEMO</small></b></div>):<Empty id="discoveries-empty" title="The discoveries are still ahead" description="Successful work creates one independent discovery roll. Rewards are never guaranteed."/>}</div>}
 <div className="profile-actions"><Action secondary data-testid="profile-back" onClick={()=>navigate('/agents')}>All agents</Action>{own?<Action data-testid="profile-new-mission" disabled={a.status!=='ACTIVE'} onClick={()=>navigate('/agents/'+a.id+'/mission')}>{a.status==='ACTIVE'?'Give a mission':a.status==='WORKING'?'Mission in progress':a.status==='RESTING'?'Restoring energy':'Agent is sleeping'}<ArrowRight size={16}/></Action>:<Action data-testid="profile-create-own" onClick={()=>navigate('/create')}>Create your own agent<ArrowRight size={16}/></Action>}</div></Modal>;
}