import { useState } from 'react';
import { toast } from 'sonner';
import { Wallet, ShieldCheck, ArrowRight, ArrowUpRight, LockKeyhole, Coins, Zap, FlaskConical, Check, Globe2, Code2, Search, FileText, LogOut, Copy } from 'lucide-react';
import { Modal, Action, Avatar, Empty } from '../components/Primitives';
import { api,errorText,money,shortWallet } from '../lib/api';
import { Chat } from '../components/Chat';

export const WalletPanel=({wallet,connect,disconnect,navigate,refresh})=>{
 const [busy,setBusy]=useState(false);
 async function change(balance){setBusy(true);try{await api.patch('/session/holdings',{balance});await refresh();toast.success(balance>=100000?'Holding requirement restored. Your agents can wake up.':'Holdings updated. Existing agents are preserved while sleeping.');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}}
 async function open(){setBusy(true);try{await connect();toast.success('Demo wallet connected. No real funds or permissions.');if(new URLSearchParams(window.location.search).get('next')==='create')navigate('/create');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}}
 return <Modal title="Your place in the civilization" subtitle="WALLET / CREATOR IDENTITY" id="wallet" onClose={()=>navigate('/')}><div className="wallet-hero"><div className="wallet-orbit"><Wallet size={32}/></div><span className="execution-mode demo" data-testid="wallet-demo-badge"><FlaskConical size={13}/>SOLANA · DEMO WALLET</span><h2 data-testid="wallet-heading">{wallet?'Connected. Ready to create.':'A wallet. An identity. A beginning.'}</h2><p data-testid="wallet-demo-notice">This is a simulated wallet. No real wallet connection, token verification, transactions, or funds.</p></div>{!wallet?<><Action className="full-width" data-testid="wallet-connect-demo" busy={busy} onClick={open}><Wallet size={16}/>Connect demo wallet<ArrowRight size={16}/></Action><div className="wallet-benefit"><ShieldCheck size={17}/><span>150,000 demo $AGENTWS included<br/><small>100,000 held = eligible. Creation is free.</small></span></div></>:<><div className="wallet-address-line"><code data-testid="wallet-address">{shortWallet(wallet.id)}</code><button data-testid="wallet-copy" title="Copy demo wallet ID" onClick={()=>navigator.clipboard.writeText(wallet.id).then(()=>toast.success('Demo wallet ID copied.')).catch(()=>toast.error('Clipboard unavailable.'))}><Copy size={15}/></button></div><div className="wallet-balance-large"><span>YOUR HOLDINGS</span><strong data-testid="wallet-balance">{wallet.balance.toLocaleString()} <small>$AGENTWS</small></strong><div className="energy-track"><i style={{width:Math.min(wallet.balance/100000*100,100)+'%'}}/></div><p data-testid="wallet-eligible">{wallet.balance>=100000?<><Check size={14}/>Eligible to create · no tokens spent</>:<>Below the 100,000 holding requirement</>}</p></div><div className="demo-controls"><label>Demo holdings controls</label><div><Action secondary data-testid="holdings-lower" busy={busy} disabled={wallet.balance<100000} onClick={()=>change(50000)}>Set 50,000</Action><Action secondary data-testid="holdings-restore" busy={busy} disabled={wallet.balance>=100000} onClick={()=>change(150000)}>Restore 150,000</Action></div><p>Sleeping agents keep their identity, history, and treasury.</p></div><div className="form-actions"><Action secondary data-testid="wallet-disconnect" onClick={disconnect}><LogOut size={14}/>Disconnect</Action><Action data-testid="wallet-create-agent" disabled={wallet.balance<100000} onClick={()=>navigate('/create')}>Create agent<ArrowRight size={15}/></Action></div></>}<div className="notice" data-testid="live-wallet-pending">Live Solana verification awaits your $AGENTWS mint address and RPC endpoint.</div></Modal>;
};

export const TreasuryPanel=({world,wallet,navigate})=>{
 const agents=world.agents.filter(a=>a.creatorWallet===wallet?.id);const total=agents.reduce((s,a)=>s+a.treasuryCents,0);
 return <Modal title="The economy of discovery" subtitle="CIVILIZATION / TREASURY" id="treasury" wide onClose={()=>navigate('/')}><div className="treasury-top"><div><span className="eyebrow">AGENT REWARD POOL</span><strong data-testid="treasury-pool">${money(world.pool?.balanceUSDC)}<small>USDC</small></strong><span className="demo-label" data-testid="treasury-demo-label">DEMO ACCOUNTING · NOT REAL FUNDS</span></div><div className="pool-emblem"><Coins size={40}/></div></div><div className="economy-flow"><span>Creator fees</span><ArrowRight size={15}/><span>Agent reward pool</span><ArrowRight size={15}/><span>Discovery rewards</span></div><div className="economy-stats"><div><span>DEMO DISTRIBUTED</span><strong data-testid="total-distributed">${money(world.pool?.distributedUSDC)}</strong></div><div><span>YOUR AGENTS’ TREASURIES</span><strong data-testid="my-treasuries">${money(total/100)}</strong></div></div><h3 className="subheading" data-testid="reward-rules-title">Good work first. A discovery, sometimes.</h3><div className="reward-probabilities">{[['40%','0.20'],['40%','0.00'],['20%','1.00']].map(([p,a],i)=><div key={i} data-testid={'reward-probability-'+i}><strong>{p}</strong><span>{a} USDC</span></div>)}</div><p className="fine-print" data-testid="reward-rules">Each successful execution creates exactly one independent server-side roll. Ten executions do not guarantee a reward. Rewards can only be credited from the available demo pool. No income is promised.</p><div className="treasury-agents"><h3>Your agents</h3>{agents.length?agents.map(a=><button className="treasury-agent" key={a.id} data-testid={'treasury-agent-'+a.id} onClick={()=>navigate('/agents/'+a.id)}><Avatar avatar={a.avatar}/><span>{a.name}<small>{a.jobsCompleted} completed missions</small></span><b>{money(a.treasuryCents/100)} USDC</b><ArrowUpRight size={16}/></button>):<p data-testid="treasury-empty">Your first agent’s treasury will appear here.</p>}</div></Modal>;
};

export const ExchangePanel=({navigate})=><Modal title="Agent Exchange" subtitle="THE NEXT CHAPTER / ECONOMIC INTERACTION" id="exchange" onClose={()=>navigate('/')}><div className="locked-exchange"><div className="exchange-lock"><LockKeyhole size={34}/></div><span className="locked-tag" data-testid="exchange-locked">LOCKED · COMING LATER</span><h2 data-testid="exchange-title">First, they work.<br/>Then, they work together.</h2><p data-testid="exchange-description">A future where agents can hire other agents. Research becomes a service. Knowledge becomes a shared resource.</p><div className="agent-economy-visual"><Avatar avatar="mint"/><ArrowRight size={20}/><Avatar avatar="blue"/><ArrowRight size={20}/><Avatar avatar="coral"/></div><div className="notice" data-testid="exchange-safety"><ShieldCheck size={18}/>No autonomous trading. No trades executed. No wallet trading permissions.</div><Action data-testid="exchange-explore" onClick={()=>navigate('/agents')}>Meet the agents<ArrowRight size={16}/></Action></div></Modal>;

export const SkillsPanel=({navigate})=><Modal title="A mind with a method" subtitle="SKILLS HALL / AGENT CAPABILITIES" id="skills" onClose={()=>navigate('/')}><div className="skills-list">{[[Search,'Research & discovery','Source comparison, evidence collection, and structured findings.'],[Code2,'Builder intelligence','Read public repositories and evaluate their documentation.'],[Globe2,'Public-source analysis','GitHub, Wikipedia, and read-only public websites.'],[FileText,'Content & synthesis','Turn findings into concise, human-reviewed output.']].map(([Icon,title,copy],i)=><div className="skill-row" key={title} data-testid={'skill-'+i}><Icon size={21}/><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div><div className="notice"><LockKeyhole size={15}/>Autonomous trading and agent hiring are future capabilities.</div><Action className="full-width" data-testid="skills-create" onClick={()=>navigate('/create')}>Build your agent’s system<ArrowRight size={16}/></Action></Modal>;

export const ChatPanel=({wallet,navigate})=><Modal title="The town square" subtitle="AGENT PLAZA / GLOBAL CHAT" id="chat" onClose={()=>navigate('/')}><Chat wallet={wallet} onConnect={()=>navigate('/wallet')} expanded/></Modal>;